document.addEventListener('DOMContentLoaded',()=>{requireAuth();const db=getDB();const email=activeEmail();const user=db.users.find(u=>u.email===email);if(!user)return;
document.body.classList.toggle('dark',!!db.settings.darkMode);const toggle=document.getElementById('themeToggle');if(toggle)toggle.textContent=db.settings.darkMode?'☀️ Light Mode':'🌙 Dark Mode';toggle?.addEventListener('click',()=>{db.settings.darkMode=!db.settings.darkMode;saveDB(db);location.reload()});document.getElementById('logoutBtn')?.addEventListener('click',()=>{clearSession();location.href='index.html'});
const totalIncome=db.income.salary+db.income.otherIncome;const expenses=db.transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);const incomeTx=db.transactions.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0);const total=totalIncome+incomeTx;
setText('userName',user.name);setText('income',money(total));setText('savings',money(db.savingsPlan.monthlySavings));setText('expenses',money(expenses));setText('balance',money(total-expenses));
const plan=document.getElementById('plan');if(plan){const s=db.savingsPlan.monthlySavings,n=Math.max(0,totalIncome-s);const rows=[['Needs',n*.55],['Wants',n*.25],['Emergency',n*.125],['Other',n*.075]];plan.innerHTML=rows.map(r=>`<div class="plan-row"><span>${r[0]}</span><strong>${money(r[1])}</strong></div>`).join('')}
const goal=db.savingsPlan.goalAmount||0,saved=db.savingsGoals.reduce((a,g)=>a+g.saved,0);if(document.getElementById('savingBar')){const pct=goal?Math.min(100,saved/goal*100):0;document.getElementById('savingBar').style.width=pct+'%';setText('savingText',`${money(saved)} saved of ${money(goal)} (${pct.toFixed(1)}%)`)}
const recent=document.getElementById('recentTransactions');if(recent){const arr=[...db.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);recent.innerHTML=arr.length?arr.map(t=>`<div class="transaction-row"><span>${t.description}<small class="muted"> · ${t.category} · ${t.date}</small></span><strong class="${t.type==='income'?'positive':'negative'}">${t.type==='income'?'+':'-'}${money(t.amount)}</strong></div>`).join(''):'<p class="muted">No transactions yet.</p>'}
const list=document.getElementById('transactionList');if(list){const form=document.getElementById('transactionForm');date.value=new Date().toISOString().slice(0,10);function render(){const q=(search.value||'').toLowerCase(),f=filter.value;const arr=db.transactions.filter(t=>(f==='all'||t.type===f)&&`${t.description} ${t.category}`.toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));list.innerHTML=arr.length?arr.map(t=>`<div class="transaction-row"><span><strong>${t.description}</strong><small class="muted"> · ${t.category} · ${t.date}</small></span><span><strong class="${t.type==='income'?'positive':'negative'}">${t.type==='income'?'+':'-'}${money(t.amount)}</strong> <button onclick="deleteTransaction('${t.id}')">✕</button></span></div>`).join(''):'<p class="muted">No matching transactions.</p>'}window.deleteTransaction=id=>{db.transactions=db.transactions.filter(t=>t.id!==id);saveDB(db);render()};form?.addEventListener('submit',e=>{e.preventDefault();db.transactions.push({id:Date.now().toString(),type:type.value,amount:+amount.value,description:description.value,category:category.value,date:date.value});saveDB(db);form.reset();date.value=new Date().toISOString().slice(0,10);render()});search?.addEventListener('input',render);filter?.addEventListener('change',render);render()}
const budgetForm=document.getElementById('budgetForm');if(budgetForm){function renderBudgets(){const cats=Object.keys(db.budgets);budgetList.innerHTML=cats.length?cats.map(c=>{const spent=db.transactions.filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.amount,0),limit=db.budgets[c],pct=Math.min(100,spent/limit*100);return `<div class="budget-row"><span><strong>${c}</strong><small class="muted"> · ${money(spent)} / ${money(limit)}</small></span><span class="${spent>limit?'negative':'positive'}">${spent>limit?'Over budget':'On track'} (${pct.toFixed(0)}%)</span></div>`}).join(''):'<p class="muted">No budgets set.</p>'}budgetForm.addEventListener('submit',e=>{e.preventDefault();db.budgets[budgetCategory.value]=+budgetAmount.value;saveDB(db);budgetForm.reset();renderBudgets()});renderBudgets()}
const goalForm=document.getElementById('goalForm');if(goalForm){function renderGoals(){goals.innerHTML=db.savingsGoals.length?db.savingsGoals.map(g=>{const pct=Math.min(100,g.target?g.saved/g.target*100:0);return `<div class="goal-card"><h3>🎯 ${g.name}</h3><p>${money(g.saved)} / ${money(g.target)}</p><div class="progress"><div style="width:${pct}%"></div></div><p class="muted">${pct.toFixed(1)}% · Target ${g.date}</p><button onclick="deleteGoal('${g.id}')">Delete</button></div>`}).join(''):'<p class="muted">No savings goals yet.</p>'}window.deleteGoal=id=>{db.savingsGoals=db.savingsGoals.filter(g=>g.id!==id);saveDB(db);renderGoals()};goalForm.addEventListener('submit',e=>{e.preventDefault();db.savingsGoals.push({id:Date.now().toString(),name:goalName.value,target:+goalTarget.value,saved:+goalSaved.value,date:goalDate.value});saveDB(db);goalForm.reset();renderGoals()});renderGoals()}
const profileInfo=document.getElementById('profileInfo');if(profileInfo)profileInfo.innerHTML=`<h2>${user.name}</h2><p>${user.email}</p><hr><p><strong>Monthly salary:</strong> ${money(db.income.salary)}</p><p><strong>Other income:</strong> ${money(db.income.otherIncome)}</p><p><strong>Monthly savings:</strong> ${money(db.savingsPlan.monthlySavings)}</p><p><strong>Goal:</strong> ${money(db.savingsPlan.goalAmount)}</p>`;
if(document.getElementById('incomeChart')){const income=db.income.salary+db.income.otherIncome+incomeTx;new Chart(incomeChart,{type:'bar',data:{labels:['Income','Expenses','Planned Savings'],datasets:[{label:'Amount',data:[income,expenses,db.savingsPlan.monthlySavings]}]},options:{responsive:true}});const cats={};db.transactions.filter(t=>t.type==='expense').forEach(t=>cats[t.category]=(cats[t.category]||0)+t.amount);new Chart(categoryChart,{type:'doughnut',data:{labels:Object.keys(cats),datasets:[{data:Object.values(cats)}]}});analyticsTips.innerHTML=`<p>💡 You are saving ${totalIncome?((db.savingsPlan.monthlySavings/totalIncome)*100).toFixed(1):0}% of your planned income.</p><p>💡 Total recorded expenses: ${money(expenses)}.</p>`}
});
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
